doorkeeper-gem/doorkeeper-openid_connect

README.md
lib/doorkeeper/openid_connect/config.rb
spec/lib/doorkeeper/openid_connect/config_spec.rb

Hi
I have detected `NoMethodError (undefined method expiration for #<Doorkeeper::OpenidConnect::Config:0x007ff85333c4c8>):` error.
So I have added expiration option with default value 120 seconds.
If you have any suitable defaults, could you please inform me it?
Thanks

fix no expiration option error

---

lib/doorkeeper/openid_connect/models/id_token.rb
lib/doorkeeper/openid_connect/version.rb

Usually a token recipient will either have the public cert locally or call the JWKS endpoint to retrieve the public cert if the OP supports it.

Leave out the kid parameter from the id token headers

---

lib/doorkeeper/openid_connect.rb
lib/doorkeeper/openid_connect/version.rb

This will prevent breaking grant types that are not openid connect enabled such as client_credentials.

Check the presence of id_token when rendering it in the response body

---

CHANGELOG.md
README.md
lib/doorkeeper/openid_connect/user_info.rb
spec/controllers/discovery_controller_spec.rb
spec/controllers/userinfo_controller_spec.rb
spec/dummy/config/initializers/doorkeeper_openid_connect.rb
spec/lib/user_info_spec.rb

It is occasionally useful to know _which_ scopes a calling application is using when generating claim values.
In the current implementation, `instance_eval` is used which causes unexpected context changes (`self` is the resource owner instance within the claim block which is undocumented and unexpected). Ruby's `instance_eval` also disallows additional arguments to be passed to the block.
Rather than using `instance_eval` this just `call`s the block with the resource owner and new scopes argument. Thereby sending the caller's scopes and leaving the block context unchanged.
💥  Undocumented breaking change: The context within the `normal_claim` is no longer the resource owner instance.

Send scopes to claim generators

---

CHANGELOG.md
doorkeeper-openid_connect.gemspec

This allows developers to use the current [v1.7.0 json-jwt](https://github.com/nov/json-jwt/tree/v1.7.0) release which appears to pass all current tests.

Loosen json-jwt dependency restriction to ~> 1.6.

---

CHANGELOG.md
app/controllers/doorkeeper/openid_connect/userinfo_controller.rb
lib/doorkeeper/openid_connect/id_token.rb
lib/doorkeeper/openid_connect/user_info.rb

This removes some of the surprising context changes within the configuration blocks. Specifically, `self` is no longer the caller instance. This was an undocumented and surprising side effect of using `instance_eval` to execute blocks.

Use call rather than instance_eval for configuration blocks

---

README.md
app/controllers/doorkeeper/openid_connect/discovery_controller.rb
lib/doorkeeper/openid_connect.rb
lib/doorkeeper/openid_connect/config.rb
lib/doorkeeper/openid_connect/id_token.rb
lib/generators/doorkeeper/openid_connect/templates/initializer.rb
spec/controllers/discovery_controller_spec.rb
spec/dummy/config/initializers/doorkeeper_openid_connect.rb
spec/lib/config_spec.rb
spec/lib/id_token_spec.rb
spec/lib/openid_connect_spec.rb
spec/rails_helper.rb
spec/support/doorkeeper_configuration.rb

This PR allows applications using the gem to configure the encryption type of the private key. This should allow all methods (RSA, EC, etc) supported by [json/jwt](https://github.com/nov/json-jwt/wiki/JWS) This is in response to issue: https://github.com/doorkeeper-gem/doorkeeper-openid_connect/issues/25

Add support for additional encryption methods

---

README.md
app/controllers/doorkeeper/openid_connect/discovery_controller.rb
app/controllers/doorkeeper/openid_connect/userinfo_controller.rb
lib/doorkeeper/openid_connect/config.rb
lib/doorkeeper/openid_connect/id_token.rb
lib/doorkeeper/openid_connect/user_info.rb
lib/generators/doorkeeper/openid_connect/templates/initializer.rb
spec/dummy/config/initializers/doorkeeper_openid_connect.rb
spec/lib/user_info_spec.rb

According to [OpenID Connect specification](http://openid.net/specs/openid-connect-core-1_0.html#SubjectIDTypes), we can use `pairwise` subject identifier that provides a different subject identifier to each client.
This pull request adds abillity for generating pairwise subject identifier to this gem.
How about this?

feature: Support pairwise subject identifier

---

README.md
app/controllers/doorkeeper/openid_connect/userinfo_controller.rb
lib/doorkeeper/openid_connect/user_info.rb
spec/controllers/discovery_controller_spec.rb
spec/controllers/userinfo_controller_spec.rb
spec/dummy/config/initializers/doorkeeper_openid_connect.rb
spec/lib/user_info_spec.rb

There are specific cases where we need to customize the claims returned from our `UserInfo` endpoint based on the access token, which contains information about the user, application, grant, and more.
This PR passed the `access_token` as a third argument to the claims builder.
@toupeira

Pass Access Tokens to claim builders.

---

lib/doorkeeper/openid_connect/helpers/controller.rb
spec/controllers/doorkeeper/authorizations_controller_spec.rb

Error handling currently returns a json object whose body contains the error code and description along with an HTTP status 401.  This pull-request changes the behavior of error handling in the gem to conform with [OpenID Connect 1.0 Section 3.1.2.6](http://openid.net/specs/openid-connect-core-1_0.html#AuthError):
> Unless the Redirection URI is invalid, the Authorization Server returns the
> Client to the Redirection URI specified in the Authorization Request with the
> appropriate error and state parameters. Other parameters SHOULD NOT be
> returned.

Redirect errors per Section 3.1.2.6 of OpenID Connect 1.0

---

lib/doorkeeper/openid_connect/oauth/token_response.rb
spec/lib/oauth/token_response_spec.rb

This adds the id_token as part of the refresh token response as permitted by the OIDC spec:
> the response body is the Token Response of Section 3.1.3.3 except that it might not contain an id_token
Many OIDC providers, like Google, have that behavior so it's used in things like Kubernetes:
> Providers that don’t return an id_token as part of their refresh token response (e.g. Okta) aren’t supported by this plugin and should use “Option 2” below.
[source](https://kubernetes.io/docs/admin/authentication/#option-1---oidc-authenticator)
See also https://gitlab.com/gitlab-org/gitlab-ce/issues/44485

Set id_token when nil (RefreshToken)

---

README.md

`jws_private_key` [is deprecated](https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/cdabae87f814877b1c4631a638f0ba6ca3af334d/lib/doorkeeper/openid_connect/config.rb#L31) and the initializer template was updated to reflect that but the readme wasn't updated.

Update deprecated `jws_private_key` config item

---

doorkeeper-openid_connect.gemspec

closes #54 
@toupeira hey, I tested my production app with latest Doorkeeper release candidate and all my tests are green so I think we can let people use it with Doorkeeper OpenidConnect.

Loose doorkeeper version.

---

lib/doorkeeper/openid_connect/helpers/controller.rb
spec/dummy/db/migrate/20180904152859_add_confidential_to_applications.rb
spec/dummy/db/schema.rb
spec/lib/oauth/token_response_spec.rb

Didn't realize that Travis was still pulling 4.x for https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/55, in the meantime Doorkeeper 5.0 came out of RC and broke our build :(
Had to change the DB schema (see https://github.com/doorkeeper-gem/doorkeeper/wiki/Migration-from-old-versions) and adjust the specs a little bit.

Changes for Doorkeeper 5.0

---

lib/doorkeeper/oauth/id_token_token_response.rb

For context, Doorkeeper recommends extending the token response with custom attributes by defining a module that overrides `body`, and prepending it to Doorkeeper::OAuth::Token response. In fact, this is the exact practice Doorkeeper OpenID Connect uses:
https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/master/lib/doorkeeper/openid_connect/oauth/authorization_code_request.rb#L23
In order to make extending Doorkeeper OIDC's own IdTokenTokenResponse easier, this pull request introduce a method that generates  the params hash, and makes `redirect_uri` consume that method. This means people wishing to extend the IdTokenToken  response with new parameters can prepend a module that defines `redirect_uri_params` and
invokes `super`, rather than having to reimplement all of …

Separate id-token-token URL generation from params

---

lib/doorkeeper/openid_connect/helpers/controller.rb
spec/controllers/doorkeeper/authorizations_controller_spec.rb

Fixes https://github.com/doorkeeper-gem/doorkeeper-openid_connect/issues/61

Validate redirect_uri when handling custom params

---

lib/doorkeeper/openid_connect.rb
spec/controllers/discovery_controller_spec.rb
spec/lib/openid_connect_spec.rb

This change fixes the DiscoveryController#keys JSON response
not being compliant with RFC 7518 (JWA), when representing the
parameters for Elliptic Curve Keys.
See: https://tools.ietf.org/html/rfc7518#section-6.2.1
Closes #68

Add 'crv' param to normalized EC signing key

---

doorkeeper-openid_connect.gemspec

since #67, doorkeeper-open-id_connect has called an API (`#mapping`) that was introduced in doorkeeper 5.0. (https://github.com/doorkeeper-gem/doorkeeper/pull/1082/files#diff-30d1c02eb523d3fdbe0ea87cd811bc3fR7)
See more here: https://github.com/doorkeeper-gem/doorkeeper-openid_connect/commit/3893ea1318e302a078272ff408aff1c50bef85d1#r32599682

fix runtime dependency

---

app/controllers/doorkeeper/openid_connect/discovery_controller.rb
spec/controllers/discovery_controller_spec.rb

This PR adds `revocation_endpoint` and `introspection_endpoint` keys to `/.well-known/openid-configuration` response.
Although non-standard, there're multiple examples that provide those keys:
- https://accounts.google.com/.well-known/openid-configuration
- https://developer.okta.com/docs/api/resources/oidc/#response-properties-7
- https://connect2id.com/products/server/docs/api/discovery#openid-config
- https://developers.onelogin.com/openid-connect/api/provider-config
Taking into the consideration that doorkeeper already provides those endpoints, I think it makes sense to mention them in the discovery response as well.

Add revocation_endpoint and introspection_endpoint to .well-known

---

lib/doorkeeper/openid_connect/oauth/password_access_token_request.rb

When using Doorkeeper strategy hook the `response.id_token` was nil:
```
after_successful_strategy_response do |request, response|
puts "#{response.id_token.inspect}" # nil
end
```
The fix is to return `super` in Doorkeeper hook `after_successful_strategy_response`  
It returns a `Doorkeeper::OAuth::TokenResponse` with two attributes:  
`@token` of class `Doorkeeper::AccessToken`  
`@id_token` of class `Doorkeeper::OpenidConnect::IdToken`
Before:
```
[2] pry(#<Doorkeeper::Config::Builder>)> response
=> #<Doorkeeper::OAuth::TokenResponse:0x00007ffe8324dcc0
@token=
#<Doorkeeper::AccessToken:0x00007ffe8310e760
id: 175,
resource_owner_id: 1,
application_id: 1,
token: "YkKr-j3ize0*************WIUGb42rS1QIGzfQkiZM",
refresh_token: nil,
expires_in: 7200,
revoked_at: nil,
created_at: Wed, 22 May …
```

Fix Password after_successful_response so the id_token is not nil in Doorkeeper hook after_successful_strategy_response

---

lib/doorkeeper/openid_connect/helpers/controller.rb
spec/controllers/doorkeeper/authorizations_controller_spec.rb

This should fix https://github.com/doorkeeper-gem/doorkeeper-openid_connect/issues/78, by adding back the check for `pre_auth.client` which was removed in https://github.com/doorkeeper-gem/doorkeeper-openid_connect/commit/3893ea1
Also, refactor `Doorkeeper::OpenidConnect::Helpers::Controller` a bit:
- include `oidc` in all custom method names to protect against name clashes with the `doorkeeper` gem
- split out `oidc_authorization_request?` and `handle_oidc_error!`
Thanks to @cincospenguinos @urnf @isabellechalhoub for the inspiration! :wink:

Check for client presence in controller

---

lib/doorkeeper/openid_connect/helpers/controller.rb
spec/controllers/doorkeeper/authorizations_controller_spec.rb

This PR fixes an issue I've experienced when doing silent authentication together with
```
skip_authorization do |resource_owner, client|
true
end
```
setting in `Doorkeeper.configure`. Silent authorization will pass `prompt=none` which will check if there are any existing tokens in `matching_tokens_for_oidc_resource_owner`. This check is not needed when `skip_authorization` is set to true.

Allow silent authentication without user consent

---

.travis.yml
CHANGELOG.md
Gemfile
doorkeeper-openid_connect.gemspec
lib/doorkeeper/openid_connect/errors.rb
lib/doorkeeper/openid_connect/helpers/controller.rb
lib/doorkeeper/openid_connect/oauth/pre_authorization.rb
lib/doorkeeper/openid_connect/version.rb
spec/controllers/doorkeeper/authorizations_controller_spec.rb
spec/dummy/db/schema.rb
spec/lib/oauth/pre_authorization_spec.rb
spec/lib/oauth/token_response_spec.rb

Closes https://github.com/doorkeeper-gem/doorkeeper-openid_connect/issues/88

Changes for Doorkeeper 5.2

---

doorkeeper-openid_connect.gemspec
lib/doorkeeper/openid_connect/version.rb

See - https://nvd.nist.gov/vuln/detail/CVE-2019-18848

Bump json-jwt because of CVE-2019-18848

---

CHANGELOG.md
app/controllers/doorkeeper/authorizations_controller.rb
lib/doorkeeper/oauth/id_token_request.rb
lib/doorkeeper/openid_connect/helpers/controller.rb
lib/doorkeeper/openid_connect/oauth/pre_authorization.rb
spec/controllers/doorkeeper/authorizations_controller_spec.rb
spec/lib/oauth/id_token_request_spec.rb
spec/lib/oauth/id_token_token_request_spec.rb
spec/lib/oauth/pre_authorization_spec.rb

#85 tried to make doorkeeper-openid_connect to be compatible with doorkeeper 5.2, but there are errors to be fixed and some place to refactor. So I create this PR to "completely" make this gem compatible with doorkeeper 5.2.
- Resolves #95 
- set response_on_fragment for pre_auth.error_response
- Refactor code.
The work is explained as PR's comment below 👇

Update changes for Doorkeeper 5.2

---

lib/doorkeeper/openid_connect/id_token.rb
spec/lib/id_token_spec.rb

Audience method returns an error if called when the application on the access token is null. I have changed it to return null instead
`NoMethodError: undefined method `uid' for nil:NilClass`
```
"/code/masterlock/doorkeeper-openid_connect/lib/doorkeeper/openid_connect/id_token.rb:49:in `audience'",
"/code/masterlock/doorkeeper-openid_connect/lib/doorkeeper/openid_connect/id_token.rb:19:in `claims'",
"/code/masterlock/doorkeeper-openid_connect/lib/doorkeeper/openid_connect/id_token.rb:28:in `as_json'",
"/code/masterlock/doorkeeper-openid_connect/lib/doorkeeper/openid_connect/id_token.rb:32:in `as_jws_token'",
"/code/masterlock/doorkeeper-openid_connect/lib/doorkeeper/openid_connect/oauth/token_response.rb:12:in `body'",
"/code/masterlock/doorkeeper/app/controllers/doorkeeper/tokens_controll …
```

Fix audience method for null application

---

lib/generators/doorkeeper/openid_connect/templates/migration.rb.erb
spec/models/access_grant_spec.rb

This fix closes #82
This change works only for new installations for this gem, since the fix is made in the migration template, which is only used during a fresh install.
For existing users who wish to avail the changes to fix the issue, please consider generating a new migration in your application which drops the existing `foreign_key` in the `oauth_openid_requests` table and then creating a new `foreign_key` in it's place with `on_delete: :cascade` included.
Example:
```ruby
class UpdateOauthOpenIdRequestsForeignKeys < ActiveRecord::Migration[5.2]
def up
remove_foreign_key(:oauth_openid_requests, column: :access_grant_id)
add_foreign_key(:oauth_openid_requests, :oauth_access_grants, column: :access_grant_id, on_delete: :cascade)
end
def down
remove_foreign_key(:oauth_openid_requests, …
```

Use cascading deletes for deleting oauth_openid_requests upon deleting an access_grant

---

app/controllers/doorkeeper/authorizations_controller.rb
doorkeeper-openid_connect.gemspec
lib/doorkeeper/oauth/id_token_request.rb
lib/doorkeeper/openid_connect/helpers/controller.rb
lib/doorkeeper/openid_connect/oauth/authorization/code.rb
lib/doorkeeper/openid_connect/oauth/pre_authorization.rb
spec/lib/oauth/authorization_code_request_spec.rb
spec/lib/oauth/id_token_request_spec.rb
spec/lib/oauth/id_token_response_spec.rb
spec/lib/oauth/id_token_token_request_spec.rb
spec/lib/oauth/id_token_token_response_spec.rb
spec/lib/oauth/password_access_token_request_spec.rb

Doorkeeper 5.4 has some internals refactoring which breaks it to use with doorkeeper openid connect.
This PR solves the issue while staying backward compatible with Doorkeeper < 5.4

Add support for Doorkeeper 5.4

---

README.md
app/controllers/doorkeeper/openid_connect/discovery_controller.rb
lib/doorkeeper/openid_connect/config.rb
spec/controllers/discovery_controller_spec.rb
spec/lib/config_spec.rb

This is in the spec for discovery:
https://openid.net/specs/openid-connect-discovery-1_0.html
And in the spec for RP-Initiated Logout:
https://openid.net/specs/openid-connect-session-1_0.html#RPLogout
And used by popular libraries like:
https://github.com/IdentityModel/oidc-client-js
When you trigger the `userUnloaded` event with `oidc-client-js`, it will print the following error in the browser console when used with `doorkeeper-openid_connect`:
With the end_session_endpoint configured like in this PR, `oidc-client-js` will work as expected when emitting the `userUnloaded` event (running the client side hook and then redirecting to the specified url).
If you want to use named routes inside the initializer, you can do it like so:
```
end_session_endpoint do …
```

Add support for end_session_endpoint

---

CHANGELOG.md
app/controllers/doorkeeper/openid_connect/userinfo_controller.rb

If you run this in a Rails 5 API application you will get an <ArgumentError: Before process_action callback :verify_authenticity_token has not been defined> error
Resolves #114

API mode will not define the verify_authenticity_token action

---

CHANGELOG.md
app/controllers/doorkeeper/openid_connect/discovery_controller.rb
spec/controllers/discovery_controller_spec.rb

Resolves #106 
Commit#1: Add grant types supported to discovery
Commit#2: fix code style following rubocop rule
This is the list grant types defined in Doorkeeper: https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/oauth.rb
To get grant types supported by AS:
- User [grant_flows of doorkeeper configuration](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/config.rb#L267) to get:
- authorization_code
- implicit
- password
- client_credentials
- Use [use_refresh_token of doorkeeper configuration](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/config.rb#L122-L128) to add `refresh_token` grant types as [calculate_token_grant_types](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/config.rb#L597)

Add grant_types_supported to discovery response

---

CHANGELOG.md
README.md
config/locales/en.yml
lib/doorkeeper/openid_connect/config.rb
lib/doorkeeper/openid_connect/errors.rb
lib/doorkeeper/openid_connect/helpers/controller.rb
lib/generators/doorkeeper/openid_connect/templates/initializer.rb
spec/controllers/doorkeeper/authorizations_controller_spec.rb
spec/dummy/config/initializers/doorkeeper_openid_connect.rb
spec/dummy/config/locales/doorkeeper_openid_connect.en.yml
spec/lib/config_spec.rb

Add `select_account_for_resource_owner` configuration to allow defining behavior when receiving param `prompt=select_account` at authorization request.
Resolves #107

Add configuration for prompt=select_account

---

CHANGELOG.md
lib/generators/doorkeeper/openid_connect/templates/migration.rb.erb
spec/dummy/db/schema.rb

Fix migration template to use `references` migrations DSL to properly create column type.
Also add an index for referenced column.
Fixes #115

Fix migration template to use Rails migrations DSL for association

---

lib/doorkeeper/openid_connect.rb
lib/doorkeeper/openid_connect/helpers/controller.rb
lib/doorkeeper/openid_connect/oauth/pre_authorization.rb
lib/doorkeeper/openid_connect/response_mode.rb
spec/controllers/doorkeeper/authorizations_controller_spec.rb
spec/lib/response_mode_spec.rb

We noticed that when using the `promt=none` option our client did not parse the returned login error.
This was due to that the computed redirect url for errors used query strings instead of fragments even if the response_type was of the id_token type. 
This PR aims to ensure that the same response mode is used regardless on success or error as per https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthError 
> If the End-User denies the request or the End-User authentication fails, the Authorization Server MUST return the error Authorization Response in the fragment component of the Redirection URI …  unless a different Response Mode was specified.
and https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#Combinations
> When supplied as the value for the …

Bug fix: Fragment urls for implicit flow error redirects

---

app/controllers/doorkeeper/openid_connect/discovery_controller.rb
spec/controllers/discovery_controller_spec.rb
spec/lib/config_spec.rb

Allows the application to use the configured host etc in url builders without having to set them again for the specific call.
Rationale is that it is cumbersome enough as it is to maintain this for mailers

Execute end_session_endpoint in the controllers context

---

.rubocop.yml
lib/doorkeeper/openid_connect/orm/active_record/request.rb

This reference to `ApplicationRecord` is causing an error when initializing in Rails 6:
DEPRECATION WARNING: Initialization autoloaded the constant ApplicationRecord. (ActiveSupport::DeprecationException)
This is a change in the way Rails 6 does autoloading; it looks like this was done to appease rubocop's style rules, which shouldn't apply to this situation.

Remove reference to ApplicationRecord

---

app/controllers/doorkeeper/openid_connect/discovery_controller.rb

Without cloning the array, the original doorkeeper configuration's `grant_flows` would be mutated, so that multiple calls would lead to multiple 'refresh_token's filling up the array.
This would look as follows when visiting the discovery endpoint (3 times):
```
grant_types_supported: [
"authorization_code",
"refresh_token",
"refresh_token",
"refresh_token
],
```
With the change in this MR it should look like this, even after multiple calls:
```
grant_types_supported: [
"authorization_code",
"refresh_token"
],
```

Clone doorkeeper.grant_flows array before appending 'refresh_token'

---

.ruby-gemset
README.md
app/controllers/doorkeeper/openid_connect/discovery_controller.rb
lib/doorkeeper/openid_connect/config.rb
spec/controllers/discovery_controller_spec.rb
spec/lib/config_spec.rb

Like described from @steti in PR #90, this is a re-work to be able to configure all discovery endpoint URL generations.
Example:
```ruby
Doorkeeper::OpenidConnect.configure do
discovery_url_options do |request| 
{
authorization: { host: 'alternate-authorization.host' },
token: { host: 'alternate-token.host' },
revocation: { host: 'alternate-revocation.host' },
introspection: { host: 'alternate-introspection.host' },
userinfo: { host: 'alternate-userinfo.host' },
jwks: { host: 'alternate-jwks.host', protocol: request.ssl? ? :https : :http }
}
end
end
```
or for only one endpoint:
```ruby
Doorkeeper::OpenidConnect.configure do
discovery_url_options do
{  authorization: { host: 'alternate-authorization.host' } }
end
end
```

Add discovery_url_options option for discovery endpoints URL generation.

---

app/controllers/doorkeeper/openid_connect/userinfo_controller.rb

The following error has occurred when accessing `GET /oauth/userinfo` with Doorkeeper 5.2.6 + doorkeeper-openid_connect 1.7.4:
```
ActionController::RoutingError (undefined method `config' for Doorkeeper:Module
Did you mean?  configure):
F, [2020-11-09T19:36:45.191126 #16] FATAL -- : [866e7cd8-dd2a-4868-b1d9-1dff5caae0bf]   
F, [2020-11-09T19:36:45.191227 #16] FATAL -- : [866e7cd8-dd2a-4868-b1d9-1dff5caae0bf] doorkeeper-openid_connect (1.7.4) app/controllers/doorkeeper/openid_connect/userinfo_controller.rb:6:in `<class:UserinfoController>'
doorkeeper-openid_connect (1.7.4) app/controllers/doorkeeper/openid_connect/userinfo_controller.rb:5:in `<module:OpenidConnect>'
doorkeeper-openid_connect (1.7.4) app/controllers/doorkeeper/openid_connect/userinfo_controller.rb:4:in …
```

Avoid to use the config alias while supporting Doorkeeper 5.2

---

lib/doorkeeper/openid_connect/id_token.rb
lib/generators/doorkeeper/openid_connect/templates/initializer.rb
spec/lib/config_spec.rb

Proposing a small change here so that `issuer` accepts a string or a block. This is useful in cases where Doorkeeper API mode is enabled and requests are proxied from multiple hosts, so that the value may be set dynamically from the resource owner and/or application. Please let me know if you have any concerns. Thanks!

Update issuer configuration to allow dynamic values

---

lib/doorkeeper/openid_connect.rb
spec/lib/openid_connect_spec.rb

This replaces https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/143 to resolve some merge conflicts.
Thanks to @paukul for the contribution! :heart:

Register token flows with the strategy instead of the token class

---

CHANGELOG.md
README.md
lib/doorkeeper/openid_connect/version.rb

This gem now requires Doorkeeper 5.5 and Ruby 2.5.
- [#138] Support form_post response mode (thanks to @linhdangduy)
- [#144] Support block syntax for `issuer` configuration (thanks to @maxxsnake)
- [#145] Register token flows with the strategy instead of the token class (thanks to @paukul)

Release version 1.8.0-rc1

---

CHANGELOG.md
lib/doorkeeper/openid_connect/oauth/password_access_token_request.rb
spec/lib/oauth/password_access_token_request_spec.rb

doorkeeper 5.5 added a new parameter `credentials` to `Doorkeeper::Oauth::PasswordAccessTokenRequest.initialize` resulting in ArgumentError thrown. See [this issue](https://github.com/doorkeeper-gem/doorkeeper-openid_connect/issues/151).
Once we match the parameters in the methods, we can set `skip_client_authentication_for_password_grant` to `true` and it works just fine.

Update password_access_token_request.rb to match method parameters in doorkeeper 5.5

---

README.md
app/controllers/doorkeeper/openid_connect/discovery_controller.rb
spec/controllers/discovery_controller_spec.rb

`issuer` block introduced in #144 breaks the `.well-known/openid-connect` response
when configuring issuer using a block
```
Doorkeeper::OpenidConnect.configure do
issuer do |resource_owner, application|
...
end
end
```
the `DiscoveryController.provider` return a `issuer: {}`
this gives the user back the control

fix .well-known/openid-connect issuer {} #160

---

lib/doorkeeper/openid_connect/rails/routes.rb

See [this GitLab issue](https://gitlab.com/gitlab-org/gitlab/-/issues/233956) for more background.
In short, both of those URIs and compatible to each other and contain a similar document with possibly slightly different fields, but both allow other fields to be present. So I propose we expose the same document on both locations.
Current document is already a mix of both specs, for example, `revocation_endpoint` is in fact defined for `oauth-authorization-server` and not `openid-configuration`, but it is exposed under `openid-configuration`. Which is fine.
So, in short, for maximum compatibility, let's expose this on both paths.

Exposing oauth-authorization-server, too

---

doorkeeper-openid_connect.gemspec
lib/doorkeeper/openid_connect/orm/active_record.rb
lib/doorkeeper/openid_connect/orm/active_record/access_grant.rb
spec/models/access_grant_spec.rb

Doorkeeper 5.6.0.rc1 changes how the autoloading works for orms. This patch autoloads its extensions using the built-in autoloader. When used with older doorkeeper versions, the  `initialize_models!` call should continue to work.

Add support for doorkeeper 5.6.0.rc1

---

lib/doorkeeper/openid_connect/orm/active_record.rb
lib/doorkeeper/openid_connect/orm/active_record/access_grant.rb
lib/doorkeeper/openid_connect/orm/active_record/request.rb

Since this gem is hard-coding `Doorkeeper::AccessGrant` in some places, it prevents using custom doorkeeper model.
So this pull request replaces it with `Doorkeeper.config.access_grant_model` with doorkeeper gem version check.

allow to use custom doorkeeper access grant model

---

app/controllers/doorkeeper/openid_connect/discovery_controller.rb
app/controllers/doorkeeper/openid_connect/userinfo_controller.rb

This closes #169. Background is reasoned in the issue.
Initially I only wanted to raise discussion, but since I have already had a patch that can work for me I'm proceeding with opening a PR. What do you think? I appreciate any feedbacks 🙂

Controllers inherit `Doorkeeper::AppliactionMetalController`

---

app/controllers/doorkeeper/openid_connect/discovery_controller.rb
spec/controllers/discovery_controller_spec.rb

This fixes #166.
Since `oauth_introspect_url` is not available, let's workaround by checking if it can be responded to before actually calling it. Another possible solution is to replicate the same condition as doorkeeper repo, namely `Doorkeeper.config.allow_token_introspection.is_a?(FalseClass)`, which I've not chosen because I thought it'd make it more complex to depend on the configuration of a different gem.
Getting rid of `introspection_endpoint` field can be justified because it is a non-standard (as described in #72, the original PR which introduced it) and not required nor defined by [the specification of OIDC Discovery](https://openid.net/specs/openid-connect-discovery-1_0.html).
About the test case added, the entire routes must be reloaded because the configuration here is …

`introspection_endpoint` cannot be defined when token introspection is turned off

---

README.md

can't find an obvious reason why it still shows up as broken (https://app.travis-ci.com/github/doorkeeper-gem/doorkeeper-openid_connect/builds/238272096), but at least the link to the build pipeline can be found

update travis-ci.org badge to travis-ci.com

---

doorkeeper-openid_connect.gemspec

The `json-jwt` version used by the current gem is [incompatible with OpenSSL 3.0](https://github.com/nov/json-jwt/pull/102). This is especially a problem with operating systems that are only shipped with OpenSSL 3.0 like Ubuntu 22.04 LTS.

Update json-jwt version for OpenSSL 3

---

CHANGELOG.md
app/controllers/doorkeeper/openid_connect/discovery_controller.rb
spec/controllers/discovery_controller_spec.rb
spec/dummy/db/migrate/20221122044143_enable_pkce.rb
spec/dummy/db/schema.rb
spec/lib/oauth/authorization/code_spec.rb

RFC 8414 Section 2 (https://www.rfc-editor.org/rfc/rfc8414#section-2) says `code_challenge_methods_supported` must be listed to indicate that the authorization server supports PKCE. Doorkeeper only supports `plain` and `S256`, so return that if PKCE is enabled.

Add PKCE support to OpenID discovery endpoint

---

CHANGELOG.md
lib/doorkeeper/openid_connect/helpers/controller.rb
spec/controllers/doorkeeper/authorizations_controller_spec.rb

current `doorkeeper-openid_connect` implementation always renders consent screen when `prompt=consent` is requested.
however, user can be **_non-authenticated_** status when requesting.
in that case, application tend to redirect to login page, and it conflicts with rendering consent screen, and results in `AbstractController::DoubleRenderError` error.
this pull request stop rendering consent screen when user is not authenticated, and will render consent screen after the user is authenticated.

stop render consent screen when user is not logged-in

---

lib/doorkeeper/openid_connect/orm/active_record.rb

Don't call active_record_options for Doorkeeper >= 5.6.3

---

.github/workflows/ci.yml
CHANGELOG.md
doorkeeper-openid_connect.gemspec
gemfiles/rails_5.0.gemfile
gemfiles/rails_5.2.gemfile

Ruby 3.2 is out and 2.6 has reached the EOL:
https://www.ruby-lang.org/en/downloads/branches/
Also since Rails 5 has been dropped support for and
corresponding gemfiles are now dispensable to ci.
This is a follow-up to what I have committed to doorkeeper gem in https://github.com/doorkeeper-gem/doorkeeper/pull/1618.  I guess it would be great if the CI setup mirrors what doorkeeper has just like #175 has achieved it.
As 2.6 is dropped from CI I'm including the change that bumps the required ruby version. What do you think?

Bump the range of supported Ruby and Rails versions

---

lib/doorkeeper/openid_connect.rb
lib/doorkeeper/openid_connect/id_token.rb
spec/dummy/config/initializers/jwt.rb
spec/lib/id_token_spec.rb
spec/lib/openid_connect_spec.rb

Using this gem along with the `doorkeeper-jwt` gem caused problems because that gem defines a `Doorkeeper::JWT` constant, so the autoloader thinks it should load `JWT::JWK` and other constants under the `JWT` namespace from there since this gem is also under the `Doorkeeper` namespace. The solution is to prefix the `JWT` uses with `::`.
Fixes #187.

Fix dookeeper-jwt compatibility

---

spec/lib/oauth/authorization/code_spec.rb

https://github.com/doorkeeper-gem/doorkeeper/pull/1602 added custom fields, and the tests need to be adjusted to expect the call to `custom_access_token_attributes` for `preauth`.

Fix tests for doorkeeper v5.6.5

---

CHANGELOG.md
lib/doorkeeper/openid_connect.rb
spec/dummy/config/initializers/jwt.rb
spec/rails_helper.rb

The switch from the `json-jwt` to `jwt` gem in #177 changed the default `kid` generation from RFC 7638
(https://www.rfc-editor.org/rfc/rfc7638) to a format based on the SHA256 digest of the key elements.
However, clients may fail if the the `kid` generated by `IdToken` does not match a key listed in JWKS discovery endpoint, which may be implemented by the application using RFC 7638-based `kid` values. To restore the previous behavior, applications have to set a global setting:
```
JWT.configuration.jwk.kid_generator_type = :rfc7638_thumbprint
```
However, relying on this global setting is not ideal since other keys may depend on the legacy `kid` values.
In keeping with semantic versioning, restore the `kid` generation to RFC 7638. Whether this should be customizable can be discussed …

Default to RFC 7638 kid fingerprint generation

---

.gitignore
lib/doorkeeper/openid_connect/id_token.rb

Along with #193, upgrade from 1.8.3 -> 1.8.5 caused and incident for us because of the underlying library changing and not having `typ: 'JWT'` in the header any more
While that's an optional part of the JWT spec, some client libraries are expecting that so I propose we add it back

Add back typ=JWT to header

---

.github/workflows/ci.yml
doorkeeper-openid_connect.gemspec
spec/controllers/doorkeeper/authorizations_controller_spec.rb
spec/dummy/config/environments/test.rb

The tests were failing because the current gemspec allows sqlite3 >= 1.3.6, but the external Gemfiles used older versions.
To avoid this, BUNDLE_GEMFILE needs to be set as documented in https://github.com/ruby/setup-ruby:
To use a Gemfile which is not at the root or has a different name, set BUNDLE_GEMFILE in the env at the job level as shown in the example.

ci: make all tests pass again

---

lib/doorkeeper/openid_connect/id_token.rb
spec/lib/id_token_spec.rb

In some use cases we need to specify a different expiration time for specific tokens, e.g. in our company we create tokens for admins who can access the applications as if they were the customer by using what we call "impersonated sessions". In this scenario we want shorter IdTokens.
I imagine there could be multiple scenarios where we don't want to use the global expiration time configured. I hope this will help.

Configuration per IdToken expiration

---

.github/workflows/ci.yml
CHANGELOG.md
gemfiles/rails_7.1.gemfile
gemfiles/rails_7.2.gemfile
gemfiles/rails_8.0.gemfile

Rails 7.1, 7.2, 8.0 are out
corresponding gemfiles are now dispensable to ci.
https://rubyonrails.org/maintenance
This is a follow-up to what I have committed to doorkeeper gem in https://github.com/doorkeeper-gem/doorkeeper/pull/1752.
I guess it would be great if the CI setup mirrors what doorkeeper has just like https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/182 has achieved it.

Test against Rails 7.1, 7.2, 8.0

---

doorkeeper-openid_connect.gemspec

As per issue #210 we're seeing the following warning when testing our project on ruby 3.4.0-rc1:
doorkeeper-openid_connect-1.8.10/lib/doorkeeper/openid_connect/claims_builder.rb:3: warning: ~/.rbenv/versions/3.4.0-rc1/lib/ruby/3.4.0+1/ostruct.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
This PR adds `ostruct` as a dependency in the gemspec to remove this warning.

Add ostruct gem to gemspec to fix ruby 3.4 warning (fixes #210)

---

.github/workflows/ci.yml
CHANGELOG.md
gemfiles/rails_7.0.gemfile

> NameError:
>  uninitialized constant ActiveSupport::LoggerThreadSafeLevel::Logger
See: https://github.com/ruby-concurrency/concurrent-ruby/pull/1062
> LoadError:
> cannot load such file -- logger
Exclude the combination of Ruby head and Rails 7.0
This is a follow-up to what I have committed to doorkeeper gem in https://github.com/doorkeeper-gem/doorkeeper/pull/1760.
I guess it would be great if the CI setup mirrors what doorkeeper has just like https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/215 has achieved it.

Bump the range of supported Ruby versions
